#!/usr/bin/env python3
"""Generate living architecture documentation from CloudFormation templates.

For every directory under the IaC root that contains a ``template.yaml`` (or
``template.yml``), this writes a ``README.md`` next to it containing Mermaid
diagrams and reference tables derived straight from the template.

The output is a pure function of the template: no timestamps, no commit SHAs,
nothing that changes between runs. That means CI can regenerate on every push
and only produce a commit when the architecture actually changed.

Usage
-----
    python3 scripts/gen-arch-docs.py                 # write docs
    python3 scripts/gen-arch-docs.py --check         # fail if docs are stale
    python3 scripts/gen-arch-docs.py --root iac      # override the IaC root
    python3 scripts/gen-arch-docs.py --index         # also write an index at the root

Generated files are marked, and the generator refuses to overwrite anything that
lacks the marker or that git tracks but the worktree is missing.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

try:
    import yaml
except ImportError:  # pragma: no cover - dependency guard
    sys.exit("PyYAML is required: pip install pyyaml")


GENERATED_MARKER = "<!-- generated by scripts/gen-arch-docs.py -- do not edit by hand -->"

# Resource types that the network and security diagrams already cover, so the
# component-dependency graph stays readable.
COMPONENT_EXCLUDE_TYPES = {
    "AWS::EC2::VPC",
    "AWS::EC2::VPCCidrBlock",
    "AWS::EC2::Subnet",
    "AWS::EC2::RouteTable",
    "AWS::EC2::Route",
    "AWS::EC2::SubnetRouteTableAssociation",
    "AWS::EC2::InternetGateway",
    "AWS::EC2::EgressOnlyInternetGateway",
    "AWS::EC2::VPCGatewayAttachment",
    "AWS::EC2::NatGateway",
    "AWS::EC2::EIP",
    "AWS::EC2::VPCEndpoint",
    "AWS::EC2::SecurityGroup",
    "AWS::EC2::SecurityGroupIngress",
    "AWS::EC2::SecurityGroupEgress",
}

# Types whose loss is not recoverable by re-running the template.
STATEFUL_TYPES = {
    "AWS::RDS::DBInstance",
    "AWS::RDS::DBCluster",
    "AWS::DynamoDB::Table",
    "AWS::S3::Bucket",
    "AWS::EFS::FileSystem",
    "AWS::ElastiCache::CacheCluster",
    "AWS::Redshift::Cluster",
}

SG_PROPERTY_NAMES = ("SecurityGroups", "SecurityGroupIds", "VPCSecurityGroups", "VpcSecurityGroupIds")

OPEN_V4 = "0.0.0.0/0"
OPEN_V6 = "::/0"


# --------------------------------------------------------------------------- #
# CloudFormation-aware YAML loading
# --------------------------------------------------------------------------- #


class CfnLoader(yaml.SafeLoader):
    """SafeLoader that understands CloudFormation short-form intrinsics."""


def _cfn_multi_constructor(loader: CfnLoader, tag_suffix: str, node: yaml.Node) -> dict:
    key = "Ref" if tag_suffix == "Ref" else f"Fn::{tag_suffix}"
    if isinstance(node, yaml.ScalarNode):
        value: Any = loader.construct_scalar(node)
        if key == "Fn::GetAtt" and isinstance(value, str):
            value = value.split(".")
    elif isinstance(node, yaml.SequenceNode):
        value = loader.construct_sequence(node, deep=True)
    else:
        value = loader.construct_mapping(node, deep=True)
    return {key: value}


CfnLoader.add_multi_constructor("!", _cfn_multi_constructor)


# --------------------------------------------------------------------------- #
# Intrinsic rendering
# --------------------------------------------------------------------------- #

PSEUDO_PARAMS = {
    "AWS::Region": "<region>",
    "AWS::AccountId": "<account-id>",
    "AWS::Partition": "aws",
    "AWS::StackName": "<stack-name>",
    "AWS::URLSuffix": "amazonaws.com",
    "AWS::NoValue": "",
}


class Template:
    """A parsed template plus helpers for resolving intrinsics to readable text."""

    def __init__(self, path: Path):
        self.path = path
        self.raw_bytes = path.read_bytes()
        self.doc: dict = yaml.load(self.raw_bytes, Loader=CfnLoader) or {}
        self.parameters: dict = self.doc.get("Parameters") or {}
        self.mappings: dict = self.doc.get("Mappings") or {}
        self.conditions: dict = self.doc.get("Conditions") or {}
        self.resources: dict = self.doc.get("Resources") or {}
        self.outputs: dict = self.doc.get("Outputs") or {}
        self.description: str = str(self.doc.get("Description") or "").strip()

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.raw_bytes).hexdigest()

    def param_default(self, name: str) -> str | None:
        param = self.parameters.get(name)
        if not isinstance(param, dict) or "Default" not in param:
            return None
        return str(param["Default"])

    def render(self, value: Any) -> str:
        """Best-effort human-readable rendering of a property value."""
        if value is None:
            return ""
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float, str)):
            return str(value)
        if isinstance(value, list):
            return ", ".join(self.render(item) for item in value)
        if not isinstance(value, dict):
            return str(value)

        if "Ref" in value:
            target = value["Ref"]
            if target in PSEUDO_PARAMS:
                return PSEUDO_PARAMS[target]
            default = self.param_default(target)
            return default if default is not None else str(target)

        for key, raw in value.items():
            if key == "Fn::Sub":
                return self._render_sub(raw)
            if key == "Fn::GetAtt":
                parts = raw if isinstance(raw, list) else str(raw).split(".")
                return ".".join(str(p) for p in parts)
            if key == "Fn::FindInMap":
                return self._render_find_in_map(raw)
            if key == "Fn::Select":
                return self._render_select(raw)
            if key == "Fn::GetAZs":
                return "AZs in region"
            if key == "Fn::Join":
                delim, items = raw[0], raw[1]
                return str(delim).join(self.render(i) for i in items)
            if key == "Fn::If":
                cond, when_true, when_false = raw
                return f"if {cond}: {self.render(when_true)} else {self.render(when_false)}"
            if key == "Fn::Equals":
                return f"{self.render(raw[0])} == {self.render(raw[1])}"
            if key == "Fn::Not":
                return f"not ({self.render(raw[0])})"
            if key == "Fn::And":
                return " and ".join(f"({self.render(i)})" for i in raw)
            if key == "Fn::Or":
                return " or ".join(f"({self.render(i)})" for i in raw)
            if key == "Fn::ImportValue":
                return f"import {self.render(raw)}"
            if key == "Condition":
                return f"condition {raw}"
        # Unknown structure: render deterministically rather than guessing.
        return ", ".join(f"{k}={self.render(v)}" for k, v in sorted(value.items()))

    def _render_sub(self, raw: Any) -> str:
        if isinstance(raw, list):
            body, local_vars = str(raw[0]), raw[1] or {}
        else:
            body, local_vars = str(raw), {}

        def substitute(match: re.Match[str]) -> str:
            name = match.group(1)
            if name in local_vars:
                return self.render(local_vars[name])
            if name in PSEUDO_PARAMS:
                return PSEUDO_PARAMS[name]
            default = self.param_default(name)
            if default is not None:
                return default
            if "." in name:  # GetAtt form inside Sub
                return name
            return f"<{name}>"

        return re.sub(r"\$\{([^}]+)\}", substitute, body)

    def _render_find_in_map(self, raw: Any) -> str:
        try:
            map_name, top, second = (self.render(part) for part in raw[:3])
            return str(self.mappings[map_name][top][second])
        except Exception:
            return "|".join(self.render(part) for part in raw)

    def _render_select(self, raw: Any) -> str:
        index_raw, source = raw[0], raw[1]
        try:
            index = int(self.render(index_raw))
        except (TypeError, ValueError):
            return f"select {self.render(index_raw)} of {self.render(source)}"
        if isinstance(source, dict) and "Fn::GetAZs" in source:
            return az_letter(index)
        if isinstance(source, list):
            return self.render(source[index])
        return f"select {index} of {self.render(source)}"

    def az_index(self, value: Any) -> int | None:
        """Extract the AZ index from ``!Select [n, !GetAZs ""]``."""
        if isinstance(value, dict) and "Fn::Select" in value:
            index_raw, source = value["Fn::Select"][0], value["Fn::Select"][1]
            if isinstance(source, dict) and "Fn::GetAZs" in source:
                try:
                    return int(self.render(index_raw))
                except (TypeError, ValueError):
                    return None
        return None

    def refs_in(self, value: Any) -> set[str]:
        """Every logical resource id referenced anywhere inside ``value``."""
        found: set[str] = set()
        if isinstance(value, dict):
            for key, raw in value.items():
                if key == "Ref" and isinstance(raw, str) and raw in self.resources:
                    found.add(raw)
                elif key == "Fn::GetAtt":
                    parts = raw if isinstance(raw, list) else str(raw).split(".")
                    if parts and str(parts[0]) in self.resources:
                        found.add(str(parts[0]))
                else:
                    found |= self.refs_in(raw)
        elif isinstance(value, list):
            for item in value:
                found |= self.refs_in(item)
        return found


    # -- conditions -------------------------------------------------------- #

    def render_expr(self, value: Any) -> str:
        """Like ``render`` but keeps parameter names instead of substituting defaults.

        Used for conditions, where ``EnableReadReplica == "true"`` is informative and
        ``true == true`` is not.
        """
        if isinstance(value, dict):
            if "Ref" in value:
                target = value["Ref"]
                return PSEUDO_PARAMS.get(target, str(target))
            for key, raw in value.items():
                if key == "Fn::Equals":
                    return f"{self.render_expr(raw[0])} == {self.render_expr(raw[1])}"
                if key == "Fn::Not":
                    return f"not ({self.render_expr(raw[0])})"
                if key == "Fn::And":
                    return " and ".join(f"({self.render_expr(i)})" for i in raw)
                if key == "Fn::Or":
                    return " or ".join(f"({self.render_expr(i)})" for i in raw)
                if key == "Condition":
                    return str(raw)
        if isinstance(value, str):
            return f'"{value}"' if not value.startswith("$") else value
        return self.render(value)

    def eval_condition(self, name: str, seen: frozenset[str] = frozenset()) -> bool | None:
        """Evaluate a condition using parameter defaults. ``None`` when undecidable."""
        if name in seen or name not in self.conditions:
            return None
        return self._eval(self.conditions[name], seen | {name})

    def _eval(self, expr: Any, seen: frozenset[str]) -> bool | None:
        if isinstance(expr, bool):
            return expr
        if not isinstance(expr, dict):
            return None
        for key, raw in expr.items():
            if key == "Fn::Equals":
                left, right = self.render(raw[0]), self.render(raw[1])
                return left == right
            if key == "Fn::Not":
                inner = self._eval(raw[0], seen)
                return None if inner is None else not inner
            if key == "Fn::And":
                results = [self._eval(i, seen) for i in raw]
                return None if None in results else all(results)
            if key == "Fn::Or":
                results = [self._eval(i, seen) for i in raw]
                return None if None in results else any(results)
            if key == "Condition":
                return self.eval_condition(str(raw), seen)
        return None

    def description_blockquote(self) -> list[str]:
        """Render the template Description as a Markdown blockquote, paragraphs intact."""
        if not self.description:
            return []
        paragraphs = [p.strip() for p in self.description.split("\n") if p.strip()]
        out: list[str] = []
        for i, paragraph in enumerate(paragraphs):
            if i:
                out.append(">")
            out.append(f"> {paragraph}")
        return out


def az_letter(index: int) -> str:
    return chr(ord("a") + index) if 0 <= index < 26 else str(index)


# --------------------------------------------------------------------------- #
# Model extraction
# --------------------------------------------------------------------------- #


class Model:
    """Structured view of the template, derived generically from resource types."""

    def __init__(self, template: Template):
        self.t = template
        res = template.resources

        self.by_type: dict[str, list[str]] = defaultdict(list)
        for logical_id, body in sorted(res.items()):
            self.by_type[str((body or {}).get("Type", "unknown"))].append(logical_id)

        self.vpcs = self.by_type.get("AWS::EC2::VPC", [])
        self.has_ipv6 = bool(self.by_type.get("AWS::EC2::VPCCidrBlock"))

        self.subnets = {sid: self._subnet(sid) for sid in self.by_type.get("AWS::EC2::Subnet", [])}
        self.route_tables = {
            rid: self.name_of(rid) for rid in self.by_type.get("AWS::EC2::RouteTable", [])
        }

        # subnet -> route table, from explicit associations
        self.subnet_rt: dict[str, str] = {}
        for assoc_id in self.by_type.get("AWS::EC2::SubnetRouteTableAssociation", []):
            props = self.props(assoc_id)
            subnet_refs = self.t.refs_in(props.get("SubnetId"))
            rt_refs = self.t.refs_in(props.get("RouteTableId"))
            for subnet in subnet_refs:
                for rt in rt_refs:
                    self.subnet_rt[subnet] = rt

        self.routes = [self._route(rid) for rid in self.by_type.get("AWS::EC2::Route", [])]
        self.endpoints = [self._endpoint(eid) for eid in self.by_type.get("AWS::EC2::VPCEndpoint", [])]
        self.security_groups = {
            sg: self._security_group(sg) for sg in self.by_type.get("AWS::EC2::SecurityGroup", [])
        }
        self.sg_attachments = self._sg_attachments()
        self.listeners = [
            self._listener(lid)
            for lid in self.by_type.get("AWS::ElasticLoadBalancingV2::Listener", [])
        ]

    # -- small helpers ----------------------------------------------------- #

    def body(self, logical_id: str) -> dict:
        return self.t.resources.get(logical_id) or {}

    def props(self, logical_id: str) -> dict:
        return self.body(logical_id).get("Properties") or {}

    def type_of(self, logical_id: str) -> str:
        return str(self.body(logical_id).get("Type", "unknown"))

    def condition_of(self, logical_id: str) -> str | None:
        cond = self.body(logical_id).get("Condition")
        return str(cond) if cond else None

    def tags_of(self, logical_id: str) -> dict[str, str]:
        tags = self.props(logical_id).get("Tags")
        result: dict[str, str] = {}
        if isinstance(tags, list):
            for tag in tags:
                if isinstance(tag, dict) and "Key" in tag:
                    result[str(tag["Key"])] = self.t.render(tag.get("Value"))
        elif isinstance(tags, dict):
            for key, value in tags.items():
                result[str(key)] = self.t.render(value)
        return result

    def name_of(self, logical_id: str) -> str:
        """Prefer the Name tag, then an explicit name property, then the logical id."""
        tag_name = self.tags_of(logical_id).get("Name")
        if tag_name:
            return tag_name
        props = self.props(logical_id)
        for key in ("Name", "GroupName", "DBInstanceIdentifier", "AutoScalingGroupName",
                    "LaunchTemplateName", "LogGroupName", "DBSubnetGroupName"):
            if key not in props:
                continue
            value = props[key]
            # A name that is really a reference to another resource is not a name.
            if self.t.refs_in(value):
                continue
            return self.t.render(value)
        return logical_id

    # -- extraction -------------------------------------------------------- #

    def _subnet(self, logical_id: str) -> dict:
        props = self.props(logical_id)
        tags = self.tags_of(logical_id)
        index = self.t.az_index(props.get("AvailabilityZone"))
        return {
            "id": logical_id,
            "name": tags.get("Name", logical_id),
            "tier": tags.get("Tier", "untiered"),
            "cidr": self.t.render(props.get("CidrBlock")),
            "az": az_letter(index) if index is not None else self.t.render(props.get("AvailabilityZone")),
            "public_ip_on_launch": bool(props.get("MapPublicIpOnLaunch")),
        }

    def _route(self, logical_id: str) -> dict:
        props = self.props(logical_id)
        destination = ""
        for key in ("DestinationCidrBlock", "DestinationIpv6CidrBlock", "DestinationPrefixListId"):
            if key in props:
                destination = self.t.render(props[key])
                break
        target_id, target_kind = "", ""
        for key in ("GatewayId", "NatGatewayId", "EgressOnlyInternetGatewayId", "TransitGatewayId",
                    "VpcPeeringConnectionId", "NetworkInterfaceId", "InstanceId",
                    "CarrierGatewayId", "LocalGatewayId", "VpcEndpointId"):
            if key in props:
                refs = sorted(self.t.refs_in(props[key]))
                target_id = refs[0] if refs else self.t.render(props[key])
                target_kind = key
                break
        rt_refs = sorted(self.t.refs_in(props.get("RouteTableId")))
        return {
            "id": logical_id,
            "route_table": rt_refs[0] if rt_refs else "",
            "destination": destination,
            "target": target_id,
            "target_kind": target_kind,
            "condition": self.condition_of(logical_id),
        }

    def _endpoint(self, logical_id: str) -> dict:
        props = self.props(logical_id)
        return {
            "id": logical_id,
            "service": self.t.render(props.get("ServiceName")),
            "kind": self.t.render(props.get("VpcEndpointType")) or "Gateway",
            "route_tables": sorted(self.t.refs_in(props.get("RouteTableIds"))),
            "subnets": sorted(self.t.refs_in(props.get("SubnetIds"))),
        }

    def _security_group(self, logical_id: str) -> dict:
        props = self.props(logical_id)
        rules: list[dict] = []
        inline = props.get("SecurityGroupIngress")
        if isinstance(inline, list):
            rules.extend(self._ingress_rule(rule) for rule in inline)
        # Standalone ingress resources that target this group.
        for ingress_id in self.by_type.get("AWS::EC2::SecurityGroupIngress", []):
            ingress_props = self.props(ingress_id)
            if logical_id in self.t.refs_in(ingress_props.get("GroupId")):
                rules.append(self._ingress_rule(ingress_props))
        return {
            "id": logical_id,
            "name": self.tags_of(logical_id).get("Name", logical_id),
            "description": self.t.render(props.get("GroupDescription")),
            "ingress": rules,
            "egress_restricted": "SecurityGroupEgress" in props,
        }

    def _ingress_rule(self, rule: Any) -> dict:
        if not isinstance(rule, dict):
            return {"source": self.t.render(rule), "source_kind": "unknown", "ports": "", "description": ""}
        protocol = self.t.render(rule.get("IpProtocol"))
        from_port = rule.get("FromPort")
        to_port = rule.get("ToPort")
        if from_port is None and to_port is None:
            ports = "all"
        elif str(from_port) == str(to_port):
            ports = str(self.t.render(from_port))
        else:
            ports = f"{self.t.render(from_port)}-{self.t.render(to_port)}"
        if protocol == "-1":
            protocol = "all"

        source, source_kind = "", "unknown"
        if "CidrIp" in rule:
            source, source_kind = self.t.render(rule["CidrIp"]), "cidr"
        elif "CidrIpv6" in rule:
            source, source_kind = self.t.render(rule["CidrIpv6"]), "cidr"
        elif "SourceSecurityGroupId" in rule:
            refs = sorted(self.t.refs_in(rule["SourceSecurityGroupId"]))
            source = refs[0] if refs else self.t.render(rule["SourceSecurityGroupId"])
            source_kind = "sg"
        elif "SourcePrefixListId" in rule:
            source, source_kind = self.t.render(rule["SourcePrefixListId"]), "prefix-list"

        return {
            "source": source,
            "source_kind": source_kind,
            "protocol": protocol or "tcp",
            "ports": ports,
            "description": self.t.render(rule.get("Description")),
        }

    def _sg_attachments(self) -> dict[str, list[str]]:
        attachments: dict[str, list[str]] = defaultdict(list)
        for logical_id in sorted(self.t.resources):
            if self.type_of(logical_id) == "AWS::EC2::SecurityGroup":
                continue
            body = self.body(logical_id)
            for sg in sorted(self._sg_refs(body)):
                attachments[sg].append(logical_id)
        return attachments

    def _sg_refs(self, node: Any) -> set[str]:
        found: set[str] = set()
        if isinstance(node, dict):
            for key, value in node.items():
                if key in SG_PROPERTY_NAMES:
                    found |= {r for r in self.t.refs_in(value)
                              if self.type_of(r) == "AWS::EC2::SecurityGroup"}
                else:
                    found |= self._sg_refs(value)
        elif isinstance(node, list):
            for item in node:
                found |= self._sg_refs(item)
        return found

    def _listener(self, logical_id: str) -> dict:
        props = self.props(logical_id)
        lb_refs = sorted(self.t.refs_in(props.get("LoadBalancerArn")))
        return {
            "id": logical_id,
            "load_balancer": lb_refs[0] if lb_refs else "",
            "port": self.t.render(props.get("Port")),
            "protocol": self.t.render(props.get("Protocol")),
            "has_certificate": bool(props.get("Certificates")),
        }

    # -- derived views ----------------------------------------------------- #

    def routes_for(self, route_table: str) -> list[dict]:
        return [r for r in self.routes if r["route_table"] == route_table]

    def default_routes_for_subnet(self, subnet_id: str) -> list[dict]:
        rt = self.subnet_rt.get(subnet_id)
        if not rt:
            return []
        return [r for r in self.routes_for(rt) if r["destination"] in (OPEN_V4, OPEN_V6)]

    def _tier_order(self) -> dict[str, int]:
        preferred = ["public", "edge", "dmz", "application", "app", "private", "data", "database"]
        order = {tier: i for i, tier in enumerate(preferred)}
        extras = sorted({s["tier"] for s in self.subnets.values()} - set(order))
        for i, tier in enumerate(extras):
            order[tier] = len(preferred) + i
        return order


# --------------------------------------------------------------------------- #
# Mermaid helpers
# --------------------------------------------------------------------------- #


def mm_label(text: str) -> str:
    """Escape a string so it is safe inside a quoted Mermaid label."""
    text = str(text).replace("\n", " ").strip()
    return (
        text.replace("&", "&amp;")
        .replace('"', "&quot;")
        .replace("#", "&num;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def mm_multiline(*parts: str) -> str:
    return "<br/>".join(mm_label(p) for p in parts if str(p).strip())


def mm_id(raw: str) -> str:
    """Turn arbitrary text into a stable, readable Mermaid-safe node id."""
    friendly = {OPEN_V4: "any_ipv4", OPEN_V6: "any_ipv6"}
    if str(raw) in friendly:
        return friendly[str(raw)]
    slug = re.sub(r"[^A-Za-z0-9_]", "_", str(raw)).strip("_")
    slug = re.sub(r"_{2,}", "_", slug)
    return slug if slug and slug[0].isalpha() else f"n_{slug}"


def network_diagram(model: Model) -> list[str]:
    """Topology grouped by tier, with route tables as first-class nodes.

    Routing decisions belong to a route table, not to a subnet, so drawing
    subnet -> route table -> target is both more accurate and far less noisy than
    fanning every subnet out to every gateway.
    """
    t = model.t
    lines = ["flowchart LR", '    internet(["Internet"])']

    vpc_id = model.vpcs[0] if model.vpcs else None
    if vpc_id:
        vpc_props = model.props(vpc_id)
        vpc_label = mm_multiline(
            f"VPC {model.name_of(vpc_id)}",
            f"IPv4 {t.render(vpc_props.get('CidrBlock'))}",
            "IPv6 Amazon-provided" if model.has_ipv6 else "",
        )
        lines.append(f'    subgraph {mm_id(vpc_id)}["{vpc_label}"]')
        lines.append("        direction LR")

    # --- subnets, grouped by tier ---
    tier_order = model._tier_order()
    by_tier: dict[str, list[dict]] = defaultdict(list)
    for subnet in model.subnets.values():
        by_tier[subnet["tier"]].append(subnet)
    for tier in sorted(by_tier, key=lambda x: tier_order.get(x, 99)):
        subnets = sorted(by_tier[tier], key=lambda s: (s["az"], s["name"]))
        lines.append(f'        subgraph tier_{mm_id(tier)}["{mm_label(tier)} tier"]')
        lines.append("            direction TB")
        for subnet in subnets:
            label = mm_multiline(subnet["name"], f'AZ {subnet["az"]}', subnet["cidr"])
            lines.append(f'            {mm_id(subnet["id"])}["{label}"]')
        lines.append("        end")

    # --- route tables ---
    if model.route_tables:
        lines.append('        subgraph routing["Route tables"]')
        lines.append("            direction TB")
        for rt_id in sorted(model.route_tables):
            has_default = any(
                r["destination"] in (OPEN_V4, OPEN_V6) for r in model.routes_for(rt_id)
            )
            label = mm_multiline(
                model.name_of(rt_id),
                "" if has_default else "no default route · isolated",
            )
            lines.append(f'            {mm_id(rt_id)}{{{{"{label}"}}}}')
        lines.append("        end")

    # --- gateways and endpoints ---
    gateway_types = {
        "AWS::EC2::InternetGateway": "internet gateway",
        "AWS::EC2::NatGateway": "NAT gateway",
        "AWS::EC2::EgressOnlyInternetGateway": "egress-only IGW",
        "AWS::EC2::TransitGatewayAttachment": "transit gateway attachment",
    }
    gateway_ids: list[str] = []
    endpoint_ids: list[str] = []
    lines.append('        subgraph edges_out["Gateways &amp; endpoints"]')
    lines.append("            direction TB")
    for rtype, human in gateway_types.items():
        for gid in model.by_type.get(rtype, []):
            gateway_ids.append(gid)
            extra = ""
            if rtype == "AWS::EC2::NatGateway":
                placed_in = sorted(t.refs_in(model.props(gid).get("SubnetId")))
                if placed_in and placed_in[0] in model.subnets:
                    extra = f'AZ {model.subnets[placed_in[0]]["az"]} only'
            lines.append(f'            {mm_id(gid)}[["{mm_multiline(model.name_of(gid), human, extra)}"]]')
    for endpoint in model.endpoints:
        endpoint_ids.append(endpoint["id"])
        label = mm_multiline(endpoint["service"], f'{endpoint["kind"]} endpoint', "IPv4 only"
                             if endpoint["kind"].lower() == "gateway" else "")
        lines.append(f'            {mm_id(endpoint["id"])}[/"{label}"/]')
    lines.append("        end")

    if vpc_id:
        lines.append("    end")

    # --- edges: subnet -> route table ---
    for subnet_id, rt in sorted(model.subnet_rt.items()):
        if subnet_id in model.subnets and rt in model.route_tables:
            lines.append(f"    {mm_id(subnet_id)} --> {mm_id(rt)}")

    # --- edges: route table -> target, labelled with the destination ---
    for rt_id in sorted(model.route_tables):
        for route in sorted(model.routes_for(rt_id), key=lambda r: (r["destination"], r["target"])):
            if not route["target"]:
                continue
            suffix = " (conditional)" if route["condition"] else ""
            lines.append(
                f'    {mm_id(rt_id)} -->|"{mm_label(route["destination"] + suffix)}"| {mm_id(route["target"])}'
            )
    for endpoint in model.endpoints:
        for rt in endpoint["route_tables"]:
            lines.append(f'    {mm_id(rt)} -->|"prefix list"| {mm_id(endpoint["id"])}')

    # --- edges: gateways -> internet ---
    igws = model.by_type.get("AWS::EC2::InternetGateway", [])
    for gid in igws:
        lines.append(f'    {mm_id(gid)} <-->|"ingress &amp; egress"| internet')
    for gid in model.by_type.get("AWS::EC2::NatGateway", []):
        if igws:
            lines.append(f'    {mm_id(gid)} -->|"source NAT"| {mm_id(igws[0])}')
    for gid in model.by_type.get("AWS::EC2::EgressOnlyInternetGateway", []):
        lines.append(f'    {mm_id(gid)} -->|"outbound IPv6 only"| internet')

    # --- styling ---
    lines.extend(
        [
            "    classDef publicTier fill:#fde68a,stroke:#b45309,color:#111827;",
            "    classDef appTier fill:#bfdbfe,stroke:#1d4ed8,color:#111827;",
            "    classDef dataTier fill:#fecaca,stroke:#b91c1c,color:#111827;",
            "    classDef rt fill:#ede9fe,stroke:#6d28d9,color:#111827;",
            "    classDef gw fill:#e5e7eb,stroke:#4b5563,color:#111827;",
            "    classDef ext fill:#f9fafb,stroke:#9ca3af,color:#374151,stroke-dasharray: 4 3;",
        ]
    )
    tier_class = {
        "public": "publicTier",
        "edge": "publicTier",
        "dmz": "publicTier",
        "application": "appTier",
        "app": "appTier",
        "private": "appTier",
        "data": "dataTier",
        "database": "dataTier",
    }
    by_class: dict[str, list[str]] = defaultdict(list)
    for subnet in model.subnets.values():
        by_class[tier_class.get(subnet["tier"], "gw")].append(mm_id(subnet["id"]))
    for rt_id in model.route_tables:
        by_class["rt"].append(mm_id(rt_id))
    for gid in gateway_ids + endpoint_ids:
        by_class["gw"].append(mm_id(gid))
    by_class["ext"].append("internet")
    for class_name, nodes in sorted(by_class.items()):
        if nodes:
            lines.append(f'    class {",".join(sorted(set(nodes)))} {class_name};')
    return lines


def security_diagram(model: Model) -> list[str]:
    if not model.security_groups:
        return []
    external: dict[str, str] = {}
    group_lines: list[str] = []
    edge_lines: list[str] = []

    for sg_id, sg in sorted(model.security_groups.items()):
        attached = model.sg_attachments.get(sg_id, [])
        attached_label = ", ".join(model.name_of(a) for a in attached[:3])
        if len(attached) > 3:
            attached_label += f", +{len(attached) - 3} more"
        label = mm_multiline(sg["name"], sg["description"], f"attached to: {attached_label}" if attached_label else "")
        group_lines.append(f'    {mm_id(sg_id)}["{label}"]')

    for sg_id, sg in sorted(model.security_groups.items()):
        for rule in sg["ingress"]:
            source = rule["source"]
            if not source:
                continue
            if rule["source_kind"] == "sg" and source in model.security_groups:
                src_node = mm_id(source)
            else:
                src_node = f"ext_{mm_id(source)}"
                open_to_world = source in (OPEN_V4, OPEN_V6)
                caption = "any host on the internet" if open_to_world else rule["source_kind"]
                external[src_node] = f'    {src_node}(["{mm_multiline(source, caption)}"])'
            edge_label = mm_label(f'{rule["protocol"]} {rule["ports"]}')
            edge_lines.append(f'    {src_node} -->|"{edge_label}"| {mm_id(sg_id)}')

    lines = ["flowchart LR"]
    lines += [external[key] for key in sorted(external)]
    lines += group_lines
    lines += edge_lines
    lines.append("    classDef ext fill:#f9fafb,stroke:#9ca3af,color:#374151,stroke-dasharray: 4 3;")
    if external:
        lines.append(f'    class {",".join(sorted(external))} ext;')
    return lines


def component_diagram(model: Model) -> list[str]:
    included = [
        logical_id
        for logical_id in sorted(model.t.resources)
        if model.type_of(logical_id) not in COMPONENT_EXCLUDE_TYPES
    ]
    if not included:
        return []
    included_set = set(included)
    lines = ["flowchart LR"]
    for logical_id in included:
        short_type = model.type_of(logical_id).replace("AWS::", "")
        conditional = model.condition_of(logical_id)
        label = mm_multiline(
            model.name_of(logical_id),
            short_type,
            f"only if {conditional}" if conditional else "",
        )
        shape_open, shape_close = ('[("', '")]') if model.type_of(logical_id) in STATEFUL_TYPES else ('["', '"]')
        lines.append(f"    {mm_id(logical_id)}{shape_open}{label}{shape_close}")

    for logical_id in included:
        for target in sorted(model.t.refs_in(model.body(logical_id))):
            if target in included_set and target != logical_id:
                lines.append(f"    {mm_id(logical_id)} --> {mm_id(target)}")

    conditional_nodes = [mm_id(r) for r in included if model.condition_of(r)]
    stateful_nodes = [mm_id(r) for r in included if model.type_of(r) in STATEFUL_TYPES]
    lines.append("    classDef stateful fill:#fecaca,stroke:#b91c1c,color:#111827;")
    lines.append("    classDef conditional stroke-dasharray: 5 3;")
    if stateful_nodes:
        lines.append(f'    class {",".join(sorted(set(stateful_nodes)))} stateful;')
    if conditional_nodes:
        lines.append(f'    class {",".join(sorted(set(conditional_nodes)))} conditional;')
    return lines


def lint_mermaid(block: Iterable[str], context: str) -> list[str]:
    """Cheap structural checks that catch the mistakes this generator could make."""
    problems: list[str] = []
    lines = list(block)
    depth = 0
    declared: set[str] = set()
    referenced: set[str] = set()

    for number, line in enumerate(lines, 1):
        stripped = line.strip()
        if stripped.startswith("subgraph "):
            depth += 1
            declared.add(stripped.split()[1].split("[")[0])
            continue
        if stripped == "end":
            depth -= 1
            if depth < 0:
                problems.append(f"{context}: unbalanced 'end' at line {number}")
            continue

        # An odd number of quotes means a label swallowed the rest of the line.
        if stripped.count('"') % 2:
            problems.append(f"{context}: unbalanced quotes at line {number}: {stripped}")

        # Node declaration: an id immediately followed by a shape opener.
        match = re.match(r"([A-Za-z_][A-Za-z0-9_]*)\s*[\[({]", stripped)
        if match:
            declared.add(match.group(1))
        # Edges: collect both endpoints, ignoring any quoted edge label.
        without_labels = re.sub(r'\|"[^"]*"\|', " ", stripped)
        if re.search(r"[-.=]{1,2}[->.=]*>|<[-.=]", without_labels):
            for endpoint in re.findall(r"(?:^|\s)([A-Za-z_][A-Za-z0-9_]*)(?=\s|$|\[|\(|\{)", without_labels):
                referenced.add(endpoint)

    if depth != 0:
        problems.append(f"{context}: {depth} unclosed subgraph(s)")

    # Mermaid silently invents a node for an unknown id, which hides typos.
    keywords = {"flowchart", "TB", "LR", "TD", "RL", "BT", "direction", "class", "classDef", "end"}
    for node in sorted(referenced - declared - keywords):
        problems.append(f"{context}: edge references undeclared node '{node}'")
    return problems


# --------------------------------------------------------------------------- #
# Observations
# --------------------------------------------------------------------------- #


def observations(model: Model) -> list[str]:
    notes: list[str] = []
    t = model.t

    az_count = len({s["az"] for s in model.subnets.values()})
    nat_ids = model.by_type.get("AWS::EC2::NatGateway", [])
    nat_dependent_tables = {
        r["route_table"] for r in model.routes if r["target_kind"] == "NatGatewayId"
    }
    nat_dependent_subnets = sorted(
        s for s, rt in model.subnet_rt.items() if rt in nat_dependent_tables
    )
    if len(nat_ids) == 1 and len(nat_dependent_subnets) > 1:
        nat_az = ""
        placed_in = sorted(t.refs_in(model.props(nat_ids[0]).get("SubnetId")))
        if placed_in and placed_in[0] in model.subnets:
            nat_az = f' in AZ {model.subnets[placed_in[0]]["az"]}'
        notes.append(
            f"**Single NAT gateway.** `{nat_ids[0]}`{nat_az} carries IPv4 egress for "
            f"{len(nat_dependent_subnets)} subnets across {az_count} AZs. Losing that AZ removes "
            "outbound IPv4 for the whole tier. One NAT per AZ is the fix; cost is the trade."
        )
    elif 1 < len(nat_ids) < az_count and nat_dependent_subnets:
        notes.append(
            f"**Partial NAT redundancy.** {len(nat_ids)} NAT gateways for {az_count} AZs — "
            "at least one AZ borrows egress from another."
        )

    isolated = sorted(
        model.subnets[s]["name"]
        for s, rt in model.subnet_rt.items()
        if not model.routes_for(rt) and s in model.subnets
    )
    if isolated:
        notes.append(
            "**Isolated subnets have no route table entries at all**: "
            + ", ".join(f"`{n}`" for n in isolated)
            + ". No egress path exists, which is the correct posture for a data tier."
        )

    world_open: list[str] = []
    for sg_id, sg in sorted(model.security_groups.items()):
        for rule in sg["ingress"]:
            if rule["source"] in (OPEN_V4, OPEN_V6):
                world_open.append(
                    f'`{sg["name"]}` accepts {rule["protocol"]}/{rule["ports"]} from `{rule["source"]}`'
                )
    if world_open:
        notes.append("**Internet-reachable ingress**: " + "; ".join(world_open) + ".")

    plaintext = [
        f'`{l["id"]}` on port {l["port"]} ({l["protocol"]})'
        for l in model.listeners
        if l["protocol"].upper() in {"HTTP", "TCP"} and not l["has_certificate"]
    ]
    if plaintext:
        notes.append(
            "**Listener without TLS termination**: "
            + ", ".join(plaintext)
            + ". Traffic between client and load balancer is unencrypted."
        )

    gateway_endpoints = [e for e in model.endpoints if e["kind"].lower() == "gateway"]
    if gateway_endpoints and model.has_ipv6:
        services = ", ".join(f'`{e["service"]}`' for e in gateway_endpoints)
        notes.append(
            f"**IPv4/IPv6 asymmetry.** Gateway endpoints ({services}) are IPv4-only, while the VPC "
            "has IPv6 and an egress-only IGW. IPv6-only clients cannot use those endpoints."
        )

    risky_stateful: list[str] = []
    for rtype in sorted(STATEFUL_TYPES):
        for logical_id in model.by_type.get(rtype, []):
            policy = str(model.body(logical_id).get("DeletionPolicy", "Delete (default)"))
            if policy.startswith("Delete"):
                risky_stateful.append(f"`{logical_id}` → `{policy}`")
    if risky_stateful:
        notes.append(
            "**Stateful resources that will be destroyed on stack delete**: "
            + ", ".join(risky_stateful)
            + ". Confirm that is intentional."
        )

    unencrypted: list[str] = []
    for logical_id in model.by_type.get("AWS::RDS::DBInstance", []):
        props = model.props(logical_id)
        if "SourceDBInstanceIdentifier" in props:
            continue  # replicas inherit encryption from the source
        if not props.get("StorageEncrypted"):
            unencrypted.append(f"`{logical_id}`")
    if unencrypted:
        notes.append("**Storage encryption not enabled**: " + ", ".join(unencrypted) + ".")

    conditional = [
        (logical_id, model.condition_of(logical_id))
        for logical_id in sorted(model.t.resources)
        if model.condition_of(logical_id)
    ]
    if conditional:
        rendered = ", ".join(f"`{r}` (`{c}`)" for r, c in conditional)
        notes.append(
            f"**Conditional resources — the blast-radius toggles**: {rendered}. "
            "Flipping the controlling parameter adds or removes these on the next deploy."
        )

    single_az_stateful: list[str] = []
    for logical_id in model.by_type.get("AWS::RDS::DBInstance", []):
        props = model.props(logical_id)
        if "SourceDBInstanceIdentifier" in props:
            continue
        if not props.get("MultiAZ"):
            single_az_stateful.append(f"`{logical_id}`")
    if single_az_stateful:
        notes.append("**Single-AZ database**: " + ", ".join(single_az_stateful) + ".")

    no_retention = [
        f"`{lg}`"
        for lg in model.by_type.get("AWS::Logs::LogGroup", [])
        if "RetentionInDays" not in model.props(lg)
    ]
    if no_retention:
        notes.append(
            "**Log groups retain forever**: " + ", ".join(no_retention) + ". Cost grows without bound."
        )

    if not notes:
        notes.append("No structural observations were triggered by the current checks.")
    return notes


# --------------------------------------------------------------------------- #
# Markdown assembly
# --------------------------------------------------------------------------- #


def md_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    if not rows:
        return ["_None._"]
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        cells = [str(c).replace("|", "\\|") if str(c) else "—" for c in row]
        out.append("| " + " | ".join(cells) + " |")
    return out


def mermaid_block(title: str, lines: list[str]) -> list[str]:
    if not lines:
        return []
    return [f"### {title}", "", "```mermaid", *lines, "```", ""]


def build_index(root: Path, entries: list[dict]) -> str:
    """An index at the IaC root listing every documented stack."""
    lines = [
        "# Infrastructure as code",
        "",
        GENERATED_MARKER,
        "",
        "One directory per stack. Each `README.md` below is regenerated from its "
        "template on every push — see "
        "[`.github/workflows/architecture-docs.yml`](../.github/workflows/architecture-docs.yml).",
        "",
    ]
    rows = [
        [
            f'[`{e["dir"]}`](./{e["dir"]}/)',
            f'[architecture](./{e["dir"]}/README.md)',
            f'[`{e["template"]}`](./{e["dir"]}/{e["template"]})',
            str(e["resources"]),
            e["summary"],
        ]
        for e in entries
    ]
    lines += md_table(["Stack", "Docs", "Template", "Resources", "Summary"], rows)
    lines += [""]
    return "\n".join(lines).rstrip() + "\n"


def build_readme(template: Template, model: Model) -> tuple[str, list[str]]:
    t = template
    stack_title = t.path.parent.name.replace("-", " ").replace("_", " ").title()

    net = network_diagram(model)
    sec = security_diagram(model)
    comp = component_diagram(model)

    problems = (
        lint_mermaid(net, "network diagram")
        + lint_mermaid(sec, "security diagram")
        + lint_mermaid(comp, "component diagram")
    )

    lines: list[str] = [
        f"# {stack_title} — Architecture",
        "",
        GENERATED_MARKER,
        "",
        f"Generated from [`{t.path.name}`](./{t.path.name}) by "
        "[`scripts/gen-arch-docs.py`](../../scripts/gen-arch-docs.py). "
        "Edits here are overwritten on the next push — change the template instead.",
        "",
    ]

    if t.description:
        lines += [*t.description_blockquote(), ""]

    # At a glance
    vpc_id = model.vpcs[0] if model.vpcs else None
    glance = [
        ["Resources", str(len(t.resources))],
        ["Resource types", str(len(model.by_type))],
        ["Availability zones", str(len({s["az"] for s in model.subnets.values()}))],
        ["Subnets", str(len(model.subnets))],
        ["Tiers", ", ".join(sorted({s["tier"] for s in model.subnets.values()})) or "—"],
        ["Address family", "dual-stack (IPv4 + IPv6)" if model.has_ipv6 else "IPv4 only"],
    ]
    if vpc_id:
        glance.insert(0, ["VPC CIDR", t.render(model.props(vpc_id).get("CidrBlock"))])
    glance += [
        ["Security groups", str(len(model.security_groups))],
        ["Parameters", str(len(t.parameters))],
        ["Outputs", str(len(t.outputs))],
    ]
    lines += ["## At a glance", "", *md_table(["Property", "Value"], glance), ""]

    # Diagrams
    lines += ["## Diagrams", ""]
    lines += mermaid_block("Network topology and egress paths", net)
    lines += mermaid_block("Security group reachability", sec)
    lines += mermaid_block("Component dependencies", comp)
    if comp:
        lines += [
            "Arrows point from a resource to the resources it references. Red cylinders hold state; "
            "dashed borders are conditional resources.",
            "",
        ]

    # Addressing
    tier_order = model._tier_order()
    subnet_rows = []
    for subnet in sorted(
        model.subnets.values(), key=lambda s: (tier_order.get(s["tier"], 99), s["az"], s["name"])
    ):
        rt = model.subnet_rt.get(subnet["id"], "")
        defaults = model.default_routes_for_subnet(subnet["id"])
        default_desc = (
            ", ".join(f'{d["destination"]} → {d["target"]}' for d in defaults) if defaults else "none (isolated)"
        )
        subnet_rows.append(
            [
                f'`{subnet["name"]}`',
                subnet["tier"],
                subnet["az"],
                f'`{subnet["cidr"]}`',
                "yes" if subnet["public_ip_on_launch"] else "no",
                f"`{rt}`" if rt else "unassociated",
                default_desc,
            ]
        )
    lines += [
        "## Addressing",
        "",
        *md_table(
            ["Subnet", "Tier", "AZ", "CIDR", "Auto public IP", "Route table", "Default route"],
            subnet_rows,
        ),
        "",
    ]

    # Routing
    route_rows = []
    for rt_id in sorted(model.route_tables):
        table_routes = model.routes_for(rt_id)
        attached = sorted(
            model.subnets[s]["name"] for s, r in model.subnet_rt.items() if r == rt_id and s in model.subnets
        )
        if not table_routes:
            route_rows.append([f"`{rt_id}`", "—", "—", "local only", ", ".join(attached) or "—"])
            continue
        for route in sorted(table_routes, key=lambda r: (r["destination"], r["target"])):
            route_rows.append(
                [
                    f"`{rt_id}`",
                    f'`{route["destination"]}`',
                    f'`{route["target"]}`',
                    route["target_kind"].replace("Id", "") or "—",
                    ", ".join(attached) or "—",
                ]
            )
    lines += [
        "## Routing",
        "",
        *md_table(["Route table", "Destination", "Target", "Target kind", "Associated subnets"], route_rows),
        "",
    ]

    if model.endpoints:
        endpoint_rows = [
            [
                f'`{e["id"]}`',
                f'`{e["service"]}`',
                e["kind"],
                ", ".join(f"`{r}`" for r in e["route_tables"]) or "—",
                ", ".join(f"`{s}`" for s in e["subnets"]) or "—",
            ]
            for e in model.endpoints
        ]
        lines += [
            "### VPC endpoints",
            "",
            *md_table(["Endpoint", "Service", "Type", "Route tables", "Subnets"], endpoint_rows),
            "",
        ]

    # Security groups
    sg_rows = []
    for sg_id, sg in sorted(model.security_groups.items()):
        attached = ", ".join(f"`{a}`" for a in model.sg_attachments.get(sg_id, [])) or "—"
        if not sg["ingress"]:
            sg_rows.append([f'`{sg["name"]}`', "no ingress", "—", "—", attached])
            continue
        for rule in sg["ingress"]:
            source = rule["source"]
            if rule["source_kind"] == "sg" and source in model.security_groups:
                source = model.security_groups[source]["name"]
            sg_rows.append(
                [
                    f'`{sg["name"]}`',
                    f"`{source}`",
                    f'{rule["protocol"]}/{rule["ports"]}',
                    rule["description"] or "—",
                    attached,
                ]
            )
    lines += [
        "## Security groups",
        "",
        *md_table(["Group", "Ingress source", "Protocol/port", "Description", "Attached to"], sg_rows),
        "",
    ]

    # Parameters
    param_rows = []
    for name, spec in t.parameters.items():
        spec = spec or {}
        allowed = spec.get("AllowedValues")
        constraint = ", ".join(f"`{a}`" for a in allowed) if allowed else spec.get("AllowedPattern", "")
        param_rows.append(
            [
                f"`{name}`",
                str(spec.get("Type", "String")),
                f'`{spec.get("Default")}`' if "Default" in spec else "_required_",
                f"`{constraint}`" if constraint and not allowed else (constraint or "—"),
                str(spec.get("Description", "")).strip().replace("\n", " "),
            ]
        )
    lines += ["## Parameters", "", *md_table(["Name", "Type", "Default", "Constraint", "Description"], param_rows), ""]

    if t.conditions:
        cond_rows = []
        for name, expr in t.conditions.items():
            result = t.eval_condition(name)
            cond_rows.append(
                [
                    f"`{name}`",
                    f"`{t.render_expr(expr)}`",
                    {True: "true", False: "false", None: "undetermined"}[result],
                    ", ".join(
                        f"`{r}`"
                        for r in sorted(t.resources)
                        if model.condition_of(r) == name
                    ) or "—",
                ]
            )
        lines += [
            "## Conditions",
            "",
            *md_table(["Condition", "Expression", "With parameter defaults", "Controls"], cond_rows),
            "",
        ]

    # Outputs
    def output_value(spec: dict) -> str:
        value = (spec or {}).get("Value")
        if isinstance(value, dict) and "Ref" in value and value["Ref"] in t.resources:
            return f'id of `{value["Ref"]}`'
        return f"`{t.render(value)}`"

    output_rows = [
        [
            f"`{name}`",
            str((spec or {}).get("Description", "")).strip().replace("\n", " "),
            output_value(spec),
            f'`{t.render((spec or {}).get("Export", {}).get("Name"))}`' if (spec or {}).get("Export") else "—",
        ]
        for name, spec in t.outputs.items()
    ]
    lines += ["## Outputs", "", *md_table(["Output", "Description", "Value", "Export"], output_rows), ""]

    # Observations
    lines += ["## Observations", ""]
    lines += [f"- {note}" for note in observations(model)]
    lines += [""]

    # Inventory
    inventory_rows = [
        [f"`{rtype}`", str(len(ids)), ", ".join(f"`{i}`" for i in ids)]
        for rtype, ids in sorted(model.by_type.items())
    ]
    lines += [
        "## Resource inventory",
        "",
        *md_table(["Type", "Count", "Logical IDs"], inventory_rows),
        "",
        "---",
        "",
        "## How this file stays current",
        "",
        "A GitHub Actions workflow (`.github/workflows/architecture-docs.yml`) runs the generator on "
        "every push that touches the IaC, then commits the result. The document is a deterministic "
        "function of the template — no timestamps — so a run only produces a commit when the "
        "architecture genuinely changed.",
        "",
        f"Source template SHA-256: `{t.sha256}`",
        "",
    ]

    body = "\n".join(lines).rstrip() + "\n"
    body = re.sub(r"\n{3,}", "\n\n", body)
    return body, problems


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #


def find_templates(root: Path) -> list[Path]:
    found = [p for p in sorted(root.rglob("template.yaml"))]
    found += [p for p in sorted(root.rglob("template.yml"))]
    return sorted(set(found))


def is_tracked_by_git(path: Path) -> bool:
    """True if git knows about ``path``, even when it is absent from the worktree."""
    try:
        result = subprocess.run(
            ["git", "ls-files", "--error-unmatch", "--", str(path)],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0


def sync_file(path: Path, content: str, check: bool, report: dict) -> None:
    """Write ``content`` to ``path``, or record staleness in ``--check`` mode."""
    existing = path.read_text() if path.exists() else None

    if existing == content:
        report["unchanged"] += 1
        print(f"unchanged  {path}")
        return

    if check:
        report["stale"].append(str(path))
        print(f"STALE      {path}")
        sys.stdout.writelines(
            difflib.unified_diff(
                (existing or "").splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"{path} (committed)",
                tofile=f"{path} (regenerated)",
            )
        )
        return

    if existing is not None and GENERATED_MARKER not in existing:
        raise RuntimeError(
            f"{path} exists but is not generator-owned (marker missing). "
            "Refusing to overwrite hand-written documentation."
        )
    if existing is None and is_tracked_by_git(path):
        # Tracked but absent from the worktree: someone deleted it locally. Writing
        # here would silently replace committed content that we never got to inspect.
        raise RuntimeError(
            f"{path} is tracked by git but missing from the working tree. "
            f"Restore it first (git checkout -- {path}) so its contents can be checked, "
            "or delete it from git if it is meant to be generated."
        )
    path.write_text(content)
    report["written"] += 1
    print(f"{'updated' if existing else 'created'}    {path}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="iac", help="directory to scan for templates (default: iac)")
    parser.add_argument("--check", action="store_true", help="exit non-zero if any README is stale")
    parser.add_argument(
        "--index",
        action="store_true",
        help="also write an index at the IaC root (off by default: that file is usually hand-written)",
    )
    args = parser.parse_args(argv)

    root = Path(args.root)
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 2

    templates = find_templates(root)
    if not templates:
        print(f"error: no template.y[a]ml found under {root}", file=sys.stderr)
        return 2

    report: dict = {"written": 0, "unchanged": 0, "stale": []}
    all_problems: list[str] = []
    entries: list[dict] = []

    try:
        for template_path in templates:
            template = Template(template_path)
            model = Model(template)
            content, problems = build_readme(template, model)
            all_problems += [f"{template_path}: {p}" for p in problems]

            summary = template.description.split("\n")[0].strip() if template.description else ""
            entries.append(
                {
                    "dir": template_path.parent.relative_to(root).as_posix(),
                    "template": template_path.name,
                    "resources": len(template.resources),
                    "summary": summary,
                }
            )
            sync_file(template_path.parent / "README.md", content, args.check, report)

        if args.index and entries:
            sync_file(root / "README.md", build_index(root, entries), args.check, report)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if all_problems:
        print("\nMermaid structural problems:", file=sys.stderr)
        for problem in all_problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    if args.check and report["stale"]:
        print(
            "\nArchitecture docs are out of date. Run:\n"
            f"    python3 scripts/gen-arch-docs.py --root {root}\n"
            "and commit the result.",
            file=sys.stderr,
        )
        return 1

    print(f"\ndone: {report['written']} written, {report['unchanged']} already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
